  server:
    port: 9090

  spring:
    application:
        name: auth-service

    jpa:
      databasePlatform: org.hibernate.dialect.H2Dialect

    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: password

  app:
    jwt:
      key: 5pAq6zRyX8bC3dV2wS7gN1mK9jF0hL4tUoP6iBvE3nG8xZaQrY7cW2fA # according to SHA-256 requirements
      algorithm: HS256
      issuer: http://localhost:9090
      expiresIn: 1m
