  server:
    port: 9090
  spring:
    application:
        name: auth-service
    jpa:
      databasePlatform: org.hibernate.dialect.H2Dialect

    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: password

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
    registration:
      enabled: true
    fetchRegistry: true
    registerWithEureka: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}